source.. = src/
output.. = target/classes/
bin.includes = META-INF/,\
               .,\
               OSGI-INF/com.cloudempiere.ai.provider.factory.AIProviderFactory.xml,\
               lib/anthropic-java-client-okhttp.jar,\
               lib/anthropic-java-core.jar,\
               lib/jackson-module-kotlin.jar,\
               lib/jackson-datatype-jdk8.jar,\
               lib/jackson-datatype-jsr310.jar
