output.. = target/classes/
bin.includes = .,\
               META-INF/,\
               OSGI-INF/,\
               lib/anthropic-java-client-okhttp.jar,\
               lib/anthropic-java-core.jar,\
               lib/bedrockruntime.jar,\
               lib/jackson-annotations.jar,\
               lib/jackson-core.jar,\
               lib/jackson-databind.jar,\
               lib/jackson-datatype-jdk8.jar,\
               lib/jackson-datatype-jsr310.jar,\
               lib/jackson-module-kotlin.jar,\
               lib/kotlin-reflect.jar,\
               lib/kotlin-stdlib.jar,\
               lib/okhttp.jar,\
               lib/okio.jar,\
               lib/okio-jvm.jar
