source.. = src/
output.. = target/classes/
bin.includes = .,\
               META-INF/,\
               OSGI-INF/,\
               lib/anthropic-java-client-okhttp.jar,\
               lib/anthropic-java-core.jar,\
               lib/bedrockruntime.jar,\
               lib/jackson-annotations.jar,\
               lib/jackson-core.jar,\
               lib/jackson-databind.jar,\
               lib/jackson-datatype-jdk8.jar,\
               lib/jackson-datatype-jsr310.jar,\
               lib/jackson-module-kotlin.jar,\
               lib/kotlin-reflect.jar,\
               lib/kotlin-stdlib.jar,\
               lib/netty-buffer.jar,\
               lib/netty-codec.jar,\
               lib/netty-codec-http.jar,\
               lib/netty-codec-http2.jar,\
               lib/netty-common.jar,\
               lib/netty-handler.jar,\
               lib/netty-nio-client.jar,\
               lib/netty-resolver.jar,\
               lib/netty-transport.jar,\
               lib/netty-transport-native-unix-common.jar,\
               lib/okhttp.jar,\
               lib/okio.jar,\
               lib/okio-jvm.jar,\
               lib/langchain4j.jar
